### ISSUE TITLE
el-scrollbar怎么放入el-table

### ISSUE THREAD

**Issue by zhanlijian** [qiqihaobenben/Front-End-Basics#2]
如上图是 放入el-table外层 但头部也是会滚动的   如果 放入el-table 是作用不进table 更不用说tbody

**Comment by zhanlijian** [comment]
有没有办法 嵌入 tbody

**Comment by qiqihaobenben** [comment]
不知道你有没有看过element-ui table的源码，如果想实现你的这种效果，肯定是要改源码了，但是官方实现的固定头部，body区域滚动也没有用el-scrollbar，可是试着改一下源码。

下面这张图就是源码body的外层元素。
![image](https://user-images.githubusercontent.com/17338241/44318042-c72c7880-a466-11e8-85ef-ced118030fd4.png)

**Comment by zhanlijian** [comment]
ok。谢谢 。明白了






在 2018-08-20 10:51:14，"cfangxu" <notifications@github.com> 写道：


不知道你有没有看过element-ui table的源码，如果想实现你的这种效果，肯定是要改源码了，但是官方实现的固定头部，body区域滚动也没有用el-scrollbar，可是试着改一下源码。

下面这张图就是源码body的外层元素。
